# Generated by Django 4.1.2 on 2022-12-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_not_canceled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="not_canceled",
            field=models.BooleanField(default=True),
        ),
    ]
